### ISSUE TITLE
task cannot be started

### ISSUE THREAD

**Issue by mathslimin** [Tencent/yadcc#10]
E0803 21:09:16.471520  8840 task_dispatcher.cc:314] [10.243.2.241:48228] Unrecognized compilation environment [7446218a5a1cd826cd663c99919545490da3c56af4ffd1d53d1554cd0768b0ee] is requested by [10.243.2.241].

**Comment by 0x804d8000** [comment]
Hash of compiler is compared between client and compile-server when dispatching tasks. 

This is done to:

- Allow multiple version of compiler to coexist in a cluster. 
- Avoid unwanted behavior (e.g. compilation error) due to difference between generations of compiler. 

Check if `md5sum` of compiler the on client matches the one on compile-server(s). 

If necessary, you may use `--extra_compiler_dirs` to make more compilers (including those not in `PATH`) visible to daemon on compile-server. See https://github.com/Tencent/yadcc/blob/master/yadcc/doc/daemon.md

**Comment by 0x804d8000** [comment]
By the way, you may want to check https://github.com/Tencent/yadcc/blob/master/yadcc/doc/debugging.md out to gain more insights about your cluster. From my experience, they are quite helpful when spinning up a new cluster.

**Comment by mathslimin** [comment]
[root@kwephicprb15183 ~]# which gcc
/opt/buildtools/gcc-11.1.0/bin/gcc
[root@kwephicprb15183 ~]# which g++
/opt/buildtools/gcc-11.1.0/bin/g++
[root@kwephicprb15183 ~]# curl http://localhost:8334/inspect/vars/yadcc
{
   "compilers" : null,
   "distributed_task_dispatcher" : null,
   "execution_engine" : {
      "jobs" : {
         "alive_tasks" : 0,
         "max_tasks" : 1,
         "running_tasks" : 0,
         "tasks_run_ever" : 0
      }
   },
   "local_task_mgr" : {
      "heavyweight_waiters" : 0,
      "lightweight_task_overprovisioning" : 2,
      "lightweight_waiters" : 0,
      "max_tasks" : 2,
      "running_tasks" : 0
   }
}

the client the compilers is null, but the starter has value
[root@dggpdtm00032 testcode]# curl http://localhost:8334/inspect/vars/yadcc
{
   "compilers" : {
      "/opt/buildtools/gcc-11.1.0/bin/g++" : {
         "digest" : "7446218a5a1cd826cd663c99919545490da3c56af4ffd1d53d1554cd0768b0ee",
         "mtime" : 1627991178,
         "size" : 5012464
      }
   }

**Comment by mathslimin** [comment]
daemon start script
/opt/buildtools/yadcc-bin/yadcc/daemon/yadcc-daemon --scheduler_uri=flare://10.243.2.241:8336 --cache_server_uri=flare://10.243.2.241:8337 --token=some_fancy_token  --max_remote_tasks=1 --poor_machine_threshold_processors=0

[paas@dggpdtm00032 ~]$ curl http://username:password@localhost:8336/inspect/vars/yadcc
{
   "task_dispatcher" : {
      "capacity" : 11,
      "capacity_available" : 0,
      "capacity_unavailable" : 11,
      "running_tasks" : 0,
      "servants" : [
         {
            "capacity_available" : 0,
            "current_load" : 1,
            "discovered_at" : "2021-08-04 11:26:50",
            "environments" : [
               "f5311ca14c99d30f386e8f8e66aab75d47150beeabe7f77ffe99d432c2e80077",
               "7446218a5a1cd826cd663c99919545490da3c56af4ffd1d53d1554cd0768b0ee",
               "d4d4a506b1a509997086c6048def8af9cea0f0511f671a568613237eede7d969"
            ],
            "ever_assigned_tasks" : 0,
            "expires_at" : "2021-08-04 11:29:48",
            "location" : "10.116.244.197:8335",
            "max_tasks" : 1,
            "num_processors" : 4,
            "priority" : "SERVANT_PRIORITY_USER",
            "running_tasks" : 0,
            "version" : 7
         },
         {
            "capacity_available" : 0,
            "current_load" : 1,
            "discovered_at" : "2021-08-04 11:29:36",
            "environments" : [
               "f5311ca14c99d30f386e8f8e66aab75d47150beeabe7f77ffe99d432c2e80077",
               "7446218a5a1cd826cd663c99919545490da3c56af4ffd1d53d1554cd0768b0ee",
               "d4d4a506b1a509997086c6048def8af9cea0f0511f671a568613237eede7d969"
            ],
            "ever_assigned_tasks" : 0,
            "expires_at" : "2021-08-04 11:29:48",
            "location" : "10.243.2.241:8335",
            "max_tasks" : 10,
            "num_processors" : 4,
            "priority" : "SERVANT_PRIORITY_USER",
            "running_tasks" : 0,
            "version" : 7
         }
      ],
      "servants_up" : 2
   }
}

the capacity_available = 0 in every node while max_remote_tasks is set, why?

**Comment by 0x804d8000** [comment]
I suspect that free memory on these nodes is too low (lower than `--servant_min_memory_for_accepting_new_task` specified on scheduler, which defaults to `10G`) for scheduler to dispatch tasks to them.

See https://github.com/Tencent/yadcc/blob/master/yadcc/scheduler/task_dispatcher.cc#L262 .

You may want to try specifying `--servant_min_memory_for_accepting_new_task=2G` (or lower, but see below) when starting scheduler, if your compile-server does not have a lot of memory.

I should have documented this behavior in `doc/scheduler.md` and `doc/debugging.md`.

Besides, I'm not sure if it's worth mention, but there's a similar flag `--min_memory_for_starting_new_task` can be specified on daemon, which defaults to `2G`. This is mostly a protective option (to avoid system-wide OOM, to a certain degree), and therefore I don't suggest you to override it.

**Comment by mathslimin** [comment]
The system is not running because of low memory
start scheduler like this
```
/opt/buildtools/yadcc-bin/yadcc/scheduler/yadcc-scheduler --acceptable_tokens=some_fancy_token --inspect_credential=username:password --servant_min_memory_for_accepting_new_task=2G
```
start daemon
```
/opt/buildtools/yadcc-bin/yadcc/daemon/yadcc-daemon --scheduler_uri=flare://server-ip-scheduler:8336 --cache_server_uri=flare://10.243.2.241:8337 --token=some_fancy_token  --max_remote_tasks=10 --min_memory_for_starting_new_task=2G
```
it works
