### ISSUE TITLE
daemon can not find possible compiler in ubuntu 20.04

### ISSUE THREAD

**Issue by cyqw** [Tencent/yadcc#16]
after install gcc by apt install in ubuntu 20.04
/usr/bin/gcc is a symlink file, the realpath of gcc is /usr/bin/x86_64-linux-gnu-gcc-9
the daemon can not find any compiler, because the bellow code skip symlink 

      if (S_ISLNK(buf.st_mode)) {          // Symbolic link, ignore it.
        continue;
      }

https://github.com/Tencent/yadcc/blob/3f776f9a40582c9435c06cf5e2cf83b3313f0f81/yadcc/daemon/cloud/compiler_registry.cc#L72

**Comment by 0x804d8000** [comment]
Confirming. The same issue happens on Debian 11. 

I'll fix this later.

**Comment by 0x804d8000** [comment]
Fixed by #17 .
