### ISSUE TITLE
Memory Usage for Large File Operations

### ISSUE THREAD

**Issue by XlousZ** [Tencent/yadcc#22]
```
{
    flare::NoncontiguousBuffer standard_output;
    ......
    auto result = flare::FlattenSlow(output->standard_output);
    auto deps_list = flare::Split(result, '\n');
}
```

a 400 MB file is cached in standard_output. 
After I use it, I find that the memory is still occupied and cannot be released.

**Comment by 0x804d8000** [comment]
NoncontiguousBuffer is implemented using object pool, memory reclamation may be deferred in certain cases. 

By default, several hundreds megabytes memory will be reserved by the object pool. See if memory usage keeps increasing when you cache and free more files.

**Comment by XlousZ** [comment]
Reaching %5 and no more increasing. Fortunately, my data can be processed by line. Reading data by row to avoid memory usage of large file data.
