### ISSUE TITLE
build failed, undefined reference to `idn2_xxx'

### ISSUE THREAD

**Issue by aguludunu** [Tencent/yadcc#23]
I have build yadcc suceessfully on a server but failed on another one. The error is at tho bottom.

**on the suceess server, curl's configure is without idn2:**
checking for libidn2 options with pkg-config... no
configure: IDN_LIBS: "-lidn2"
configure: IDN_LDFLAGS: ""
configure: IDN_CPPFLAGS: ""
configure: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... no
checking idn2.h usability... no
checking idn2.h presence... no
checking for idn2.h... no
configure: WARNING: Cannot find libraries for IDN support: IDN disabled

**on the failed server, there is a libidn2.so:**
checking for libidn2 options with pkg-config... found
configure: pkg-config: IDN_LIBS: "-lidn2"
configure: pkg-config: IDN_LDFLAGS: ""
configure: pkg-config: IDN_CPPFLAGS: ""
configure: pkg-config: IDN_DIR: ""
checking if idn2_lookup_ul can be linked... yes
checking idn2.h usability... yes
checking idn2.h presence... yes
checking for idn2.h... yes

But if the env has libidn2.so, why yadcc do not link it?
I don't know blade very well, it seems to be an internal tool in tencent.
I have add -lidn2 in linkflags in BLADE_ROOT, but it do not work.

=========================================================

Blade: Entering directory `/home/zhut/davidwang/yadcc'
Blade(info): Loading config file "/home/zhut/davidwang/yadcc/thirdparty/blade/blade.conf"
Blade(info): Loading config file "/home/zhut/davidwang/yadcc/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(info): Loading done.
Blade(info): Analyzing dependency graph...
Blade(info): Analyzing done.
Blade(info): Generating backend build code...
Blade(info): Generating done.
Blade(info): Building...
Blade(info): Adjust build jobs number(-j N) to be 8
[1/3] LINK BINARY build64_release/yadcc/scheduler/yadcc-scheduler
FAILED: build64_release/yadcc/scheduler/yadcc-scheduler 
g++ -o build64_release/yadcc/scheduler/yadcc-scheduler  -Wl,--no-as-needed -lpthread -static-libgcc -static-libstdc++ -Wl,--whole-archive build64_release/yadcc/api/libscheduler_proto.a build64_release/yadcc/api/libenv_desc_proto.a build64_release/flare/init/libopenssl_initializer.a build64_release/flare/rpc/protocol/http/builtin/libexposed_vars_handler.a build64_release/flare/rpc/protocol/http/builtin/libgflags_handler.a build64_release/flare/rpc/protocol/http/builtin/libmisc_handler.a build64_release/flare/rpc/protocol/http/builtin/liboptions_handler.a build64_release/flare/base/liboption.a build64_release/flare/rpc/protocol/http/builtin/libprof_cpu_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_form_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_reflect_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_statistics_handler.a build64_release/flare/rpc/protocol/http/builtin/libstatic_resource_http_handler.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_protocol.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libpoppy_protocol.a build64_release/flare/rpc/protocol/protobuf/libpoppy_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libproto_over_http_protocol.a build64_release/flare/rpc/protocol/protobuf/libqzone_protocol.a build64_release/flare/rpc/protocol/protobuf/libnslb_registration.a build64_release/flare/rpc/load_balancer/libround_robin.a build64_release/flare/rpc/name_resolver/liblist.a build64_release/flare/rpc/message_dispatcher/libcomposited.a build64_release/flare/rpc/protocol/protobuf/libbinlog_proto.a build64_release/flare/rpc/librpc_options_proto.a build64_release/flare/rpc/protocol/protobuf/libstd_protocol.a build64_release/flare/rpc/binlog/text_only/libdumper.a build64_release/flare/rpc/binlog/text_only/libbinlog_proto.a build64_release/flare/rpc/binlog/util/libproto_binlog_proto.a build64_release/flare/rpc/protocol/protobuf/librpc_meta_proto.a build64_release/flare/rpc/protocol/http/libhttp.a build64_release/flare/rpc/protocol/http/libbinlog_proto.a build64_release/flare/base/compression/libgzip.a build64_release/flare/base/compression/liblz4.a build64_release/flare/base/compression/libsnappy.a build64_release/flare/base/compression/libzstd.a -Wl,--no-whole-archive @build64_release/yadcc/scheduler/yadcc-scheduler.rsp -lresolv -lm -ldl -lpthread -lrt
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `conn_free':
url.c:(.text+0x2a6): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2c2): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2de): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2fa): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_idnconvert_hostname':
url.c:(.text+0x135b): undefined reference to `idn2_check_version'
/usr/bin/ld: url.c:(.text+0x137b): undefined reference to `idn2_lookup_ul'
/usr/bin/ld: url.c:(.text+0x139b): undefined reference to `idn2_strerror'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_free_idnconverted_hostname':
url.c:(.text+0x13d1): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_connect':
url.c:(.text+0x4769): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x4785): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x498e): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x49ac): undefined reference to `idn2_free'
collect2: error: ld returned 1 exit status
[2/3] LINK BINARY build64_release/yadcc/cache/yadcc-cache
FAILED: build64_release/yadcc/cache/yadcc-cache 
g++ -o build64_release/yadcc/cache/yadcc-cache  -Wl,--no-as-needed -lpthread -static-libgcc -static-libstdc++ -Wl,--whole-archive build64_release/yadcc/api/libcache_proto.a build64_release/yadcc/cache/libdisk_cache_engine.a build64_release/yadcc/cache/libnull_cache_engine.a build64_release/flare/init/libopenssl_initializer.a build64_release/flare/rpc/protocol/http/builtin/libexposed_vars_handler.a build64_release/flare/rpc/protocol/http/builtin/libgflags_handler.a build64_release/flare/rpc/protocol/http/builtin/libmisc_handler.a build64_release/flare/rpc/protocol/http/builtin/liboptions_handler.a build64_release/flare/base/liboption.a build64_release/flare/rpc/protocol/http/builtin/libprof_cpu_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_form_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_reflect_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_statistics_handler.a build64_release/flare/rpc/protocol/http/builtin/libstatic_resource_http_handler.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_protocol.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libpoppy_protocol.a build64_release/flare/rpc/protocol/protobuf/libpoppy_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libproto_over_http_protocol.a build64_release/flare/rpc/protocol/protobuf/libqzone_protocol.a build64_release/flare/rpc/protocol/protobuf/libnslb_registration.a build64_release/flare/rpc/load_balancer/libround_robin.a build64_release/flare/rpc/name_resolver/liblist.a build64_release/flare/rpc/message_dispatcher/libcomposited.a build64_release/flare/rpc/protocol/protobuf/libbinlog_proto.a build64_release/flare/rpc/librpc_options_proto.a build64_release/flare/rpc/protocol/protobuf/libstd_protocol.a build64_release/flare/rpc/binlog/text_only/libdumper.a build64_release/flare/rpc/binlog/text_only/libbinlog_proto.a build64_release/flare/rpc/binlog/util/libproto_binlog_proto.a build64_release/flare/rpc/protocol/protobuf/librpc_meta_proto.a build64_release/flare/rpc/protocol/http/libhttp.a build64_release/flare/rpc/protocol/http/libbinlog_proto.a build64_release/flare/base/compression/libgzip.a build64_release/flare/base/compression/liblz4.a build64_release/flare/base/compression/libsnappy.a build64_release/flare/base/compression/libzstd.a -Wl,--no-whole-archive @build64_release/yadcc/cache/yadcc-cache.rsp -lresolv -lm -ldl -lpthread -lrt
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `conn_free':
url.c:(.text+0x2a6): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2c2): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2de): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2fa): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_idnconvert_hostname':
url.c:(.text+0x135b): undefined reference to `idn2_check_version'
/usr/bin/ld: url.c:(.text+0x137b): undefined reference to `idn2_lookup_ul'
/usr/bin/ld: url.c:(.text+0x139b): undefined reference to `idn2_strerror'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_free_idnconverted_hostname':
url.c:(.text+0x13d1): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_connect':
url.c:(.text+0x4769): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x4785): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x498e): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x49ac): undefined reference to `idn2_free'
collect2: error: ld returned 1 exit status
[3/3] LINK BINARY build64_release/yadcc/daemon/yadcc-daemon
FAILED: build64_release/yadcc/daemon/yadcc-daemon 
g++ -o build64_release/yadcc/daemon/yadcc-daemon  -Wl,--no-as-needed -lpthread -static-libgcc -static-libstdc++ -Wl,--whole-archive build64_release/flare/init/libopenssl_initializer.a build64_release/flare/rpc/builtin/libtcmalloc_profiler_http_handler.a build64_release/yadcc/api/libcache_proto.a build64_release/yadcc/api/libdaemon_proto.a build64_release/yadcc/api/libscheduler_proto.a build64_release/yadcc/daemon/local/libmessages_proto.a build64_release/flare/rpc/protocol/http/builtin/libexposed_vars_handler.a build64_release/flare/rpc/protocol/http/builtin/libgflags_handler.a build64_release/flare/rpc/protocol/http/builtin/libmisc_handler.a build64_release/flare/rpc/protocol/http/builtin/liboptions_handler.a build64_release/flare/base/liboption.a build64_release/flare/rpc/protocol/http/builtin/libprof_cpu_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_form_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_reflect_handler.a build64_release/flare/rpc/protocol/http/builtin/librpc_statistics_handler.a build64_release/flare/rpc/protocol/http/builtin/libstatic_resource_http_handler.a build64_release/flare/rpc/protocol/http/libhttp.a build64_release/flare/rpc/protocol/http/libbinlog_proto.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_protocol.a build64_release/flare/rpc/protocol/protobuf/libbaidu_std_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libpoppy_protocol.a build64_release/flare/rpc/protocol/protobuf/libpoppy_rpc_meta_proto.a build64_release/flare/rpc/protocol/protobuf/libproto_over_http_protocol.a build64_release/flare/rpc/protocol/protobuf/libqzone_protocol.a build64_release/flare/rpc/protocol/protobuf/libnslb_registration.a build64_release/flare/rpc/load_balancer/libround_robin.a build64_release/flare/rpc/name_resolver/liblist.a build64_release/flare/rpc/message_dispatcher/libcomposited.a build64_release/flare/rpc/protocol/protobuf/libbinlog_proto.a build64_release/flare/rpc/librpc_options_proto.a build64_release/flare/rpc/protocol/protobuf/libstd_protocol.a build64_release/flare/rpc/binlog/text_only/libdumper.a build64_release/flare/rpc/binlog/text_only/libbinlog_proto.a build64_release/flare/rpc/binlog/util/libproto_binlog_proto.a build64_release/flare/rpc/protocol/protobuf/librpc_meta_proto.a build64_release/flare/base/compression/libgzip.a build64_release/flare/base/compression/liblz4.a build64_release/flare/base/compression/libsnappy.a build64_release/flare/base/compression/libzstd.a build64_release/yadcc/daemon/libcache_meta_proto.a build64_release/yadcc/api/libenv_desc_proto.a -Wl,--no-whole-archive @build64_release/yadcc/daemon/yadcc-daemon.rsp -lresolv -lm -ldl -lpthread -lrt
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `conn_free':
url.c:(.text+0x2a6): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2c2): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2de): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x2fa): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_idnconvert_hostname':
url.c:(.text+0x135b): undefined reference to `idn2_check_version'
/usr/bin/ld: url.c:(.text+0x137b): undefined reference to `idn2_lookup_ul'
/usr/bin/ld: url.c:(.text+0x139b): undefined reference to `idn2_strerror'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_free_idnconverted_hostname':
url.c:(.text+0x13d1): undefined reference to `idn2_free'
/usr/bin/ld: build64_release/thirdparty/curl/lib/libcurl.a(libcurl_la-url.o): in function `Curl_connect':
url.c:(.text+0x4769): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x4785): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x498e): undefined reference to `idn2_free'
/usr/bin/ld: url.c:(.text+0x49ac): undefined reference to `idn2_free'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Blade(error): Build failure.
Blade(info): Cost time 4.43s
Blade(error): Failure

**Comment by 0x804d8000** [comment]
I think we should use `--without-libidn` when configuring lib curl then.

Working on a patch.

**Comment by 0x804d8000** [comment]
I pushed a fixed to branch minor-fix (along with other minor fixes).

Alternatively, you could apply the patch below:

```diff
diff --git a/thirdparty/curl/BUILD b/thirdparty/curl/BUILD
index 31a64da..3423fff 100644
--- a/thirdparty/curl/BUILD
+++ b/thirdparty/curl/BUILD
@@ -19,6 +19,8 @@ autotools_build(
         '--disable-ldap',
         '--disable-ldaps',
         '--without-brotli',
+        '--without-libidn',
+        '--without-libidn2',
     ]),
     deps=[
         '//thirdparty/nghttp2:nghttp2',
```

 Does that branch or this patch work for you?

You might need to `rm -rf build64_*` before rebuilding, in case `blade` doesn't re-`configure` libcurl automatically.

**Comment by aguludunu** [comment]
Thanks a lot and my problem is gone :)

**Comment by 0x804d8000** [comment]
I haven't landed the fix yet.. Reopening.

**Comment by 0x804d8000** [comment]
> Thanks a lot and my problem is gone :)

Thanks for your feedback. I'll land the fix soon.
