### ISSUE TITLE
Fail to build yadcc

### ISSUE THREAD

**Issue by Domain** [Tencent/yadcc#28]
yadcc/build64_release/thirdparty/opentracing-cpp/opentracing-cpp-1.5.1/3rd_party/include/opentracing/catch2/catch.hpp:6631:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 6631 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};

glibc changed SIGSTKSZ to be a syscall instead
of being constant. #catchorg/Catch2#2178

**Comment by 0x804d8000** [comment]
Recent changes to Flare should address this issue, thanks to Tencent/flare#81. Yadcc has updated submodule accordingly.
