### ISSUE TITLE
单机测试环境下如何生成启动调度器scheduler所需要的token？

### ISSUE THREAD

**Issue by shiyi23** [Tencent/yadcc#33]
即 ./yadcc-scheduler --acceptable_tokens=some_fancy_token
这个命令的some_fancy_token应该如何生成？急，求指导 @0x804d8000 @tencent-adm @hzlzh @chen3feng @darkinsky

**Comment by 0x804d8000** [comment]
其实就是个密码，随便配一个就可以

**Comment by shiyi23** [comment]
![image](https://user-images.githubusercontent.com/40733762/176588499-b22abb89-8a7f-4ddb-a2b4-0f2eda6511ac.png)
所以像图里这样，只要输入命令后不报错就行，对吧？

**Comment by 0x804d8000** [comment]
应该可以。

日志会打到日志文件里，有必要的话运行参数可以加--logtostderr

**Comment by shiyi23** [comment]
> 应该可以。
> 
> 日志会打到日志文件里，有必要的话运行参数可以加--logtostderr



> 应该可以。
> 
> 日志会打到日志文件里，有必要的话运行参数可以加--logtostderr

多谢！
