### ISSUE TITLE
请发布一个 Release 或者打一个 tag

### ISSUE THREAD

**Issue by chencang1980** [Tencent/yadcc#35]
为了方便回溯，建议发布一个 v1.0 之类

**Comment by 0x804d8000** [comment]
感谢建议，打了个tag。

发了个release试了下，没拉到sub module，就把release又给删了。另外考虑到sub module也比较大，真打到source code的tarball也确实比较占地方，所以建议直接clone tag来编译。

**Comment by CrazyWood2020** [comment]
邮件已收到，本回复为自动回复，我将尽快与您取得联系，谢谢！
