### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by zcfh** [Tencent/yadcc#36]
```
[45/1637] MAKE //thirdparty/nghttp2:nghttp2_build
......
libtool: install: /usr/bin/install -c .libs/libnghttp2.so.14.20.0 /home/name/workspace/yadcc/build64_release/thirdparty/nghttp2/lib/libnghttp2.so.14.20.0
/usr/bin/install: cannot stat '.libs/libnghttp2.so.14.20.0': No such file or directory

ll build64_release/thirdparty/nghttp2/nghttp2-1.41.0/lib/.libs

-rw-rw-r-- 1 wuminghui03 wuminghui03 819848 Oct 13 17:46 libnghttp2.a
lrwxrwxrwx 1 wuminghui03 wuminghui03     16 Oct 13 17:46 libnghttp2.la -> ../libnghttp2.la
-rw-rw-r-- 1 wuminghui03 wuminghui03   1023 Oct 13 17:46 libnghttp2.lai
lrwxrwxrwx 1 wuminghui03 wuminghui03     21 Oct 13 17:46 libnghttp2.so -> libnghttp2.so.14.20.0
lrwxrwxrwx 1 wuminghui03 wuminghui03     21 Oct 13 17:46 libnghttp2.so.14 -> libnghttp2.so.14.20.0
-rw-rw-r-- 1 wuminghui03 wuminghui03  27264 Oct 13 17:46 nghttp2_buf.o
```
安装报错 .libs/libnghttp2.so.14.20.0 不存在，查看目录 `build64_release/thirdparty/nghttp2/nghttp2-1.41.0/lib/.libs` , 有指向  `libnghttp2.so.14.20.0` 但是这个库是不存在的，这个库应该是新构建的才对，但是并未出现这个动态库链接报错。
已经按照 REAMD 更新了submodule, 并且在 build/external/flare 指向过 `git lfs install/pull`， 是有步骤不对少拉了文件吗
机器 CentOS Linux release 7.4.1708 (Core)。

**Comment by 0x804d8000** [comment]
应该不是少拉了文件之类的，感觉是nghttp2的构建过程（用的autotools那套应该是）有问题，试试git clean . -xdf看看重新来一次OK不

**Comment by zcfh** [comment]
> 应该不是少拉了文件之类的，感觉是nghttp2的构建过程（用的autotools那套应该是）有问题，试试git clean . -xdf看看重新来一次OK不

尝试，直接直接解压，nghttp2,然后用autotools，可以构建出对应的.so，是BUILD文件的问题吗？
执行的命令: tar xjvf  nghttp2-1.41.0.tar.bz2

**Comment by zcfh** [comment]
> 应该不是少拉了文件之类的，感觉是nghttp2的构建过程（用的autotools那套应该是）有问题，试试git clean . -xdf看看重新来一次OK不

大概知道原因了，因为机器上默认的gcc版本为4.x，这里搜索了blade的文档，`export CC=/home/distcc/gcc-8.3.0/bin/gcc CXX=/home/distcc/gcc-8.3.0/bin/g++ CPP=/home/distcc/gcc-8.3.0/bin/cpp   LD=/home/distcc/gcc-8.3.0/bin/g++ `，export了这些变量来指定gcc路径。
上面出现报错，在去掉环境变量 LD=/home/distcc/gcc-8.3.0/bin/g++，就不会出现了。
另外还发现编译fmt的时候，命令中修改CXX为g++，导致环境变量不生效,命令如下。
```

 **CXX=g++ CC=gcc** cmake -DCMAKE_INSTALL_PREFIX=../ -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_EXPORT_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DFMT_TEST=OFF ../fmt-7.1.3
```
手动修改了命令后，fmt不再报错。不过还有其他三方库在报错。
所以应该如何正确指定gcc路径？

**Comment by 0x804d8000** [comment]
把gcc8的bin目录加到path最前面试试

手动改了CXX是因为有些第三方库会默认找到clang去，所以hack了一把

**Comment by zcfh** [comment]
还是不好使。

一些打印编译指令的还能手动改改。
类似,ctemplate这种的，编译指令都不打印的，完全不知道怎么改。好崩溃。。。
```
$ make -C build64_release/thirdparty/ctemplate/ctemplate-ctemplate-2.4
make: Entering directory `/home/syslab/wuminghui/yadcc/yadcc/build64_release/thirdparty/ctemplate/ctemplate-ctemplate-2.4'
make  all-am
make[1]: Entering directory `/home/syslab/wuminghui/yadcc/yadcc/build64_release/thirdparty/ctemplate/ctemplate-ctemplate-2.4'
  CXXLD    make_tpl_varnames_h
./.libs/libctemplate_nothreads.so: undefined reference to `ctemplate_htmlparser::htmlparser_new()'
./.libs/libctemplate_nothreads.so: undefined reference to `ctemplate_htmlparser::htmlparser_attr_type(ctemplate_htmlparser::htmlparser_ctx_s*)'
./.libs/libctemplate_nothreads.so: undefined reference to `ctemplate_htmlparser::htmlparser_state(ctemplate_htmlparser::htmlparser_ctx_s*)'
./.libs/libctemplate_nothreads.so: undefined reference to `typeinfo for ctemplate::BaseArena'
./.libs/libctemplate_nothreads.so: undefined reference to `ctemplate::BaseArena::~BaseArena()'
./.libs/libctemplate_nothreads.so: undefined reference to `ctemplate::BaseArena::Reset()'
```

**Comment by zcfh** [comment]
最终部分编不过的库，手动编完，在软链进build64_release中，现在编译终于通过了，期待明天能跑

**Comment by zcfh** [comment]
> 1. /home/distcc/gcc-8.3.0/bin/

看了一下，的确没有`cc`，看系统默认的`cc` 是一个`gcc`的软链，我自己手动创建一个试试。

**Comment by zcfh** [comment]
问题可能是出在：一些环境没unset掉，或是`./blade clean ...` 和 直接删除build目录的逻辑不同。
之前试过unset CXX等环境变量，同时./blade clean，但是还是有问题。今天创新打开了终端，并且删除了`build64_release`, 把gcc8的加入到PATH就可以正常编译了，不存在 `cc` 并不影响。
