### ISSUE TITLE
[yadcc arm] 资源包打包了源码目录的 libfakeroot.so， 期望打包构建出来的库

### ISSUE THREAD

**Issue by chencang1980** [Tencent/yadcc#37]
https://github.com/Tencent/yadcc/blob/3c0f34a36a664c0bd446b3fa5ed944bb0e656b0f/yadcc/client/libfakeroot/BUILD#L28

构建了一个 arm 版本 yadcc， 其中发现资源库打包比较怪，打包的不是期望的构建出来的新库， 
由于对于 blade 不熟悉， 没看出 src 中怎么引用其他库构建结果
只能是构建第一遍后，覆盖掉，然后再构建

请问这里是否可以优化呢？

**Comment by 0x804d8000** [comment]
这儿确实有问题。这儿本意是从fakeroot.c生成一个so，然后再把这个so打包到客户端里面去。

但是这个规则不太写的出来，所以直接把编译完的so塞代码库了然后写了个resource_library。

好像没啥特别好的解决方案，可能可以把x86-64/aarch64都塞代码库然后在BUILD里面按照环境区分一下来应付，但是二进制放代码库始终不是很自然。

Workaround的话可以先把这个so编译一下，然后从build64_release/下面把编译好的覆盖掉这儿的同名so。

**Comment by chencang1980** [comment]
@chen3feng  请问 BLADE 是否考虑支持这种用法呢？

**Comment by 0x804d8000** [comment]
优化的话我再看看，不知道gen_rule能不能写出来合适的规则。

确实，编译过程中生成so是最好的。但是gen_rule不一定能和resource_library搞在一起，我确认下。

**Comment by 0x804d8000** [comment]
@chencang1980 hi，介意试一下#38 对应的分支吗，我这儿没有aarch64的环境，不太好测试

**Comment by chencang1980** [comment]
> @chencang1980 hi，介意试一下#38 对应的分支吗，我这儿没有aarch64的环境，不太好测试

拉了分支验证了下，先清理了，从头构建成功了，也确认了资源正常生成到了头文件， 运行也正常。

不过我先前为了构建结果与普通构建一致， 补丁了 flare 代码，跳过 fakeroot 逻辑， 明天我还原下相关逻辑再验证下

**Comment by chencang1980** [comment]
> > @chencang1980 hi，介意试一下#38 对应的分支吗，我这儿没有aarch64的环境，不太好测试
> 
> 拉了分支验证了下，先清理了，从头构建成功了，也确认了资源正常生成到了头文件， 运行也正常。
> 
> 不过我先前为了构建结果与普通构建一致， 补丁了 flare 代码，跳过 fakeroot 逻辑， 明天我还原下相关逻辑再验证下

今天还原验证了，正常， fakeroot 逻辑也生效了， 挺好的！
