### ISSUE TITLE
yadcc编译时，提示ld链接无法找到pthread、m、c、dl等动态库

### ISSUE THREAD

**Issue by VladislausDragulia** [Tencent/yadcc#51]
这是编译日志：

[root@st1-gitci-1 yadcc]# ./blade build yadcc/...
Blade: Entering directory `/root/source/yadcc'
Blade(info): Loading config file "/root/source/yadcc/thirdparty/blade/blade.conf"
Blade(info): Loading config file "/root/source/yadcc/BLADE_ROOT"
Blade(info): Loading BUILD files...
Blade(info): Loading done.
Blade(info): Analyzing dependency graph...
Blade(info): Analyzing done.
Blade(info): Generating backend build code...
Blade(info): Generating done.
Blade(info): Building...
Blade(info): Adjust build jobs number(-j N) to be 16
[1/1781] LINK BINARY build64_release/yadcc/client/cxx/yadcc-cxx
FAILED: build64_release/yadcc/client/cxx/yadcc-cxx 
g++ -o build64_release/yadcc/client/cxx/yadcc-cxx  -Wl,--no-as-needed -lpthread -static-libgcc -static-libstdc++ @build64_release/yadcc/client/cxx/yadcc-cxx.rsp -ldl -lpthread -static
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

[2/1781] MAKE //thirdparty/ctemplate:ctemplate_build
ninja: build stopped: subcommand failed.
Blade(error): Build failure.
Blade(info): Cost time 23.6s
Blade(error): Failure

**Comment by CrazyWood2020** [comment]
邮件已收到，本回复为自动回复，我将尽快与您取得联系，谢谢！

**Comment by VladislausDragulia** [comment]
问题解决了，是因为我的环境没有安装yum -y install glibc-static

而编译yadcc-cxx时，是-static静态编译，没有安装上述工具，就会报错

**Comment by VladislausDragulia** [comment]
问题解决了，是因为我的环境没有安装yum -y install glibc-static

而编译yadcc-cxx时，是-static静态编译，没有安装上述工具，就会报错
