### ISSUE TITLE
[2023-01-29 20:02:30.532771] [INFO ] [yadcc/client/cxx/yadcc-cxx.cc:207] Failed on the cloud with [-126]. Failing back to local machine.

### ISSUE THREAD

**Issue by VladislausDragulia** [Tencent/yadcc#52]

**Comment by 0x804d8000** [comment]
Check logs of local daemon and scheduler to see if there was any error.

I suspect there was no eligible compile server in your cluster. Note that hash of the compiler on the compile server needs to match the one on client’s machine for the server to be eligible.

**Comment by VladislausDragulia** [comment]
thx
