### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by mathslimin** [Tencent/yadcc#54]
$./blade build yadcc/...
thirdparty/protobuf/bin/x86_64/protoc-3.4.1: line 1: version: command not found
thirdparty/protobuf/bin/x86_64/protoc-3.4.1: line 2: oid: command not found

**Comment by 0x804d8000** [comment]
[代码库依赖lfs](https://github.com/Tencent/yadcc#开始使用)

**Comment by mathslimin** [comment]
pre step in ubuntu20.04
sudo apt install python
sudo apt install -y git-lfs
sudo apt-get install -y libtool

build ok
