### ISSUE TITLE
yadcc v1.x 版本编译报错

### ISSUE THREAD

**Issue by BaldStrong** [Tencent/yadcc#57]
编译环境：Intel CPU，Ubuntu22.04，gcc-11.3

yadcc v1.x 版本会拉取这个版本的[flare-7a69d23](https://github.com/Tencent/flare/tree/7a69d23947e6d4871b55b6ccb4ef0ca98bdb1025)，编译出错
`/root/yadcc/build64_release/thirdparty/opentracing-cpp/opentracing-cpp-1.5.1/3rd_party/include/opentracing/catch2/catch.hpp:6631:45: error: size of array 'altStackMem' is not an integral constant-expression
 6631 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};`
后面还会报一个`error: macro "__has_attribute" requires an identifier`的错误。
手动将flare更新到master最新版本可以修复：[https://github.com/Tencent/flare/tree/365d1ac3670d21a62212251364b0b9f7e15ed07f](https://github.com/Tencent/flare/tree/365d1ac3670d21a62212251364b0b9f7e15ed07f)

**Comment by 0x804d8000** [comment]
已修复，感谢反馈。
