### ISSUE TITLE
failling back to local machine 126

### ISSUE THREAD

**Issue by mathslimin** [Tencent/yadcc#60]
build linux kernel, get some error
Failed on the cloud with [-126]. Failing back to local machine.

**Comment by 0x804d8000** [comment]
See if log file shows some error. Both daemon's and scheduler's are worth checking.

**Comment by mathslimin** [comment]
E0305 21:09:23.126313 60920 task_dispatcher.cc:320] [ip:53442] Unrecognized compilation environment [5fcbcbe856ce2a4a1dbd6bb1fd755418f325ef886a4f234650601568bcc36464] is requested by [ip].

**Comment by mathslimin** [comment]
fix this problem by change
daemon/entry.cc
commit DropPrivileges
 // DropPrivileges();
while i run as root, It drop privileges,then compiler_registry.cc can not access the compiler
