### ISSUE TITLE
--with-nghttp2 was specified but could not find libnghttp2 pkg-config file.

### ISSUE THREAD

**Issue by realikun404** [Tencent/yadcc#69]
按照安装步骤执行
git clone https://github.com/Tencent/yadcc
cd yadcc
git submodule init
git submodule update .
编译时：./blade build yadcc/...
报错：
checking whether to build with libidn2... no
checking for pkg-config... no
configure: error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file.
[284/2107] CONFIGURE //thirdparty/glog:glog_configure
ninja: build stopped: subcommand failed.
Blade(error): Build failure.
Blade(info): Cost time 1m57.3s
Blade(error): Failure
![image](https://github.com/Tencent/yadcc/assets/74243978/17b5c20b-646d-40c5-bcf3-08d94a904fb1)

**Comment by seeuswk** [comment]
> 按照安装步骤执行 git clone https://github.com/Tencent/yadcc cd yadcc git submodule init git submodule update . 编译时：./blade build yadcc/... 报错： checking whether to build with libidn2... no checking for pkg-config... no configure: error: --with-nghttp2 was specified but could not find libnghttp2 pkg-config file. [284/2107] CONFIGURE //thirdparty/glog:glog_configure ninja: build stopped: subcommand failed. Blade(error): Build failure. Blade(info): Cost time 1m57.3s Blade(error): Failure ![image](https://private-user-images.githubusercontent.com/74243978/288340325-17b5c20b-646d-40c5-bcf3-08d94a904fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNjE2NjQsIm5iZiI6MTcxODE2MTM2NCwicGF0aCI6Ii83NDI0Mzk3OC8yODgzNDAzMjUtMTdiNWMyMGItNjQ2ZC00MGM1LWJjZjMtMDhkOTRhOTA0ZmIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDAzMDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNDgyYjM3ZTM5MWZlNzBkZDA2MTRiNTBkNjVjZjI1NjBjMDQwNDBkYzA4MGI3NjE5NWNhOTZiYzZjYTQwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vp4G_wRUpG1DM_HygB5oAYLJNU0HQFGYFzH3P6PzCsw)

我也遇到这个问题了，请教一下是怎么解决的
